### ISSUE TITLE
Where is the benchmark code itself?

### ISSUE THREAD

**Issue by takiholadi** [LudwigStumpp/llm-leaderboard#1]
I mean code to get actual scores, for example for MMLU tests.

**Comment by LudwigStumpp** [comment]
Hey @takiholadi, thanks for your interest in this project. This is simply a central collection of already published eval results. If you are interested in the respective source of the numbers, the link on each number will get you to the respective source.

**Comment by takiholadi** [comment]
Hmm, in this case there is no guarantee of reproducibility.

I faced with that in different sources the source code is different for the same test. For example, MMLU may use first k samples or random k samples, and some sources use label with highest probability (for "A", "B", "C" or "D") while some use open-generation setup (may also differ).

**Comment by LudwigStumpp** [comment]
Yes that's right. Whenever possible, I try to include all the results of one benchmark run, so that all the results come from the same code. Reproducibility / trustworthiness of eval results is still a big issue.  Also I separate between zero-shot, one-shot and few-shot.
