### ISSUE TITLE
The leaderboard is inaccessible in Steamlit...

### ISSUE THREAD

**Issue by zhimin-z** [LudwigStumpp/llm-leaderboard#11]
Check https://llm-leaderboard.streamlit.app
<img width="734" alt="image" src="https://github.com/LudwigStumpp/llm-leaderboard/assets/8592144/c39da750-2c8a-4de9-85d1-8c55b68abf1f">

**Comment by hyzhak** [comment]
still doesn't work :(

**Comment by LudwigStumpp** [comment]
Should be back now
https://llm-leaderboard.streamlit.app/
